### ISSUE TITLE
Add do_action possibility to content div

### ISSUE THREAD

**Issue by BoweFrankema** [PressCrew/buddypress-links#1]
To make the Links integration seamless with all our themes we need to achieve the following in the Links templates:

	<div id="content" role="main" class="<?php do_action( 'content_class' ); ?>">

This will allow flexible sidebar/content sizes through our theme options without having to resort to a jQuery fallback. This is a much cleaner solution because layouts can not be broken due to faulty JS or slow JS loading due too lots-a-plugins :-)

**Comment by MrMaz** [comment]
bp-legacy theme is now supported which resolves this issue
