### ISSUE TITLE
Global JS and deprecated .live() function

### ISSUE THREAD

**Issue by hnla** [PressCrew/buddypress-links#33]
As of jQuery 1.7 .live() was deprecated in favour of .on()

Currently this is causing  significant failures of the plugins functionality but testing a change from .live to .on  (three instances) proves to correct problems and should be a safe change.

Currently WP 3.9.1 is running with jQuery v1.11.0

**Comment by MrMaz** [comment]
This was resolved in a commit from a few months ago
